# See http://about.travis-ci.org/docs/user/build-configuration/

language: scala

scala:
  - 2.11.6
  - 2.11.7
  - 2.11.8
  - 2.12.0
  - 2.12.1
  - 2.12.2

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  exclude:
    - scala: 2.12.0
      jdk: oraclejdk7
    - scala: 2.12.0
      jdk: openjdk7
    - scala: 2.12.1
      jdk: oraclejdk7
    - scala: 2.12.1
      jdk: openjdk7
    - scala: 2.12.2
      jdk: oraclejdk7
    - scala: 2.12.2
      jdk: openjdk7
